### ISSUE TITLE
Running this on IoT edge

### ISSUE THREAD

**Issue by kaushikCanada** [ibaiGorordo/onnx-Ultra-Fast-Lane-Detection-Inference#1]
https://github.com/Azure/live-video-analytics/tree/master/utilities/video-analysis/resnet-onnx
is it possible to run the model as shown in the link? i want to create a module out of this and run on IoT edge

**Comment by ibaiGorordo** [comment]
I have not tried it, but it should work, you can replace the ResnetModel class with the code in the ultrafastLaneDetector.y script and with few modifications it should work.

Try to give it a try and let me know if you have any issue.

Good luck
Ibai
