### ISSUE TITLE
Nivida xavier 

### ISSUE THREAD

**Issue by khaledgabr77** [ibaiGorordo/onnx-Ultra-Fast-Lane-Detection-Inference#2]
did you tested before on nvidia xavier, or do you know if it will work there?

**Comment by ibaiGorordo** [comment]
Hi, I do not own one, so I have not tested it. But if you are able to install the onnxruntime, it should work.

**Comment by khaledgabr77** [comment]
i installed onnxruntime, but it needs to upgrade pip to last one.

**Comment by khaledgabr77** [comment]
i cloned the repo `https://github.com/ibaiGorordo/onnx-Ultra-Fast-Lane-Detection-Inference.git`, installed the requirements. 
then clone this repo `https://github.com/PINTO0309/PINTO_model_zoo/tree/main/140_Ultra-Fast-Lane-Detection`,  then `download_tusimple.sh` the output file `ultra_falst_lane_detection_tusimple_288x800.onnx` will passed into python file as model. then run the python script. 
is this steps right?

**Comment by ibaiGorordo** [comment]
Everything sound good, yes. Make sure to modify the **model_path** to the path of your model.

**Comment by khaledgabr77** [comment]
Okay, i will testing on nvidia xavier now and will feedback you, if you are interest.

**Comment by khaledgabr77** [comment]
![onnxlaneline](https://user-images.githubusercontent.com/30967695/133043609-0eea429f-cbf9-4d86-a89a-8b13c07b8e2c.png)

**Comment by ibaiGorordo** [comment]
Nice! I am glad to see that it works.

Also, I have not implemented it yet, but there is also another .onnx model for lane detection here:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/141_lanenet-lane-detection

In this case, it will be necessary to modify this repository slightly to make it work.

**Comment by khaledgabr77** [comment]
i'm look for real time lane line detection, so i will test` https://github.com/ibaiGorordo/onnx-Ultra-Fast-Lane-Detection-Inference` on roads and will test `https://github.com/PINTO0309/PINTO_model_zoo/tree/main/141_lanenet-lane-detection` .
with nvidia xavier, and will feedback you toda.

**Comment by ibaiGorordo** [comment]
Thank you! I would love to hear about the inference speeds of those models.

Let me know if you face any issues.

**Comment by khaledgabr77** [comment]
![Screenshot from 2021-09-13 12-02-22](https://user-images.githubusercontent.com/30967695/133047020-5db8d1fd-4431-43ae-a6ee-5216778fb20f.png)
i start run script video but i got video like this the frames show with this type there are small delay maybe 1 to 2 minutes, but i will test again to ensure with delay time. 
i tested with changes the video quality 720, 480, 360 it's the same big delay

**Comment by khaledgabr77** [comment]
i will download the video and check if there any delay after that

**Comment by khaledgabr77** [comment]
i downloaded the video but nothing change still have a delay maybe 5 to 10 sec per frame.
i'm going to test the next one  `https://github.com/PINTO0309/PINTO_model_zoo/tree/main/141_lanenet-lane-detection`.

**Comment by khaledgabr77** [comment]
do you know how conver onnx to TensorRT?, i guess it will work fine if i converted to TensorRT

**Comment by ibaiGorordo** [comment]
Check the repository I linked, he also converted both models into TensorRT:
https://github.com/PINTO0309/PINTO_model_zoo#19-others

**Comment by khaledgabr77** [comment]
i found there are some file generated when i bash from first time  i tried to pass this file `model_float32.tflite` to python code but it's appear error.
`onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from models/saved_model_tusimple/model_full_integer_quant.tflite failed:Protobuf parsing failed.`
Do you what this mean?

**Comment by khaledgabr77** [comment]
i tried with tflite but it's slower than onnx it's like not moving. 
i need to check that gpu is running

**Comment by khaledgabr77** [comment]
can you share with me video link for your testing. 
because it's very very slow, with dealy unxpected.

**Comment by khaledgabr77** [comment]
my question when run `python3 videoLaneDetection.py` is there any option to enable GPU, the output is not accepted compare to your video `https://www.youtube.com/watch?v=0Owf6gef1Ew` this very very fast than nvidia xavier.

**Comment by ibaiGorordo** [comment]
That video was recorded in a desktop GPU, so probably will be faster. You can check if you are running in the GPU like this:
```
import onnxruntime as ort
ort.get_device()
```
It might be better to test the other model because I think it should be faster (I have not tested it yet).

**Comment by khaledgabr77** [comment]
i tried tflite but were very slow than onnx

**Comment by ibaiGorordo** [comment]
Yeah, in your case, probably the TensorRT is the best option.

**Comment by khaledgabr77** [comment]
so how i can get TensorTr form onnx or Tflite

**Comment by khaledgabr77** [comment]
`https://www.youtube.com/watch?v=Z65hbhXCnvQ ` This video with ONNX.

**Comment by khaledgabr77** [comment]
`https://www.youtube.com/watch?v=eCS6jtwo3Oo` TFLITE it's very very slow.

**Comment by khaledgabr77** [comment]
So after watching those videos what you recommend to get real time Lane Line Detection?

**Comment by ibaiGorordo** [comment]
I think there are two options for TensorRT, you can either use the onnx model but with the tensorrt library, or in the folder witht eh models, there should be a tensorrt_saved model to be used in tensorflow. I have not done any testing in tensorrt, so I might be wrong.

But, with that speed, it might be worth to switch to the other model.

**Comment by khaledgabr77** [comment]
i didn't find inside model_saved tensorRT. 
do you have any recommdation for other models?

**Comment by ibaiGorordo** [comment]
You can either try with the other model I mentioned (lanenet).

Or another option is to try some of the models in this repository (But it is probably harder to setup):
https://github.com/Turoad/lanedet

So, probably start with lanenet.

**Comment by khaledgabr77** [comment]
So, i will try lannet first and show results with you.
also will work on lanedet for comparing. 
thanks for you effort.

**Comment by ibaiGorordo** [comment]
Good luck!

**Comment by khaledgabr77** [comment]
I have new news it's working fine now. on nvidia it's has some delay but it's acceptable for now. 
also i will test on real road tomorrow and let you know, i'm looking for small speed we will as maximum 20k/h.
`https://youtu.be/yBmcYDke7Wg`

**Comment by ibaiGorordo** [comment]
Yeah that looks much better.

Also, you might find interesting this project also in Xabier but he even combines depth estimation, segmentation and object detection:
https://github.com/iwatake2222/self-driving-ish_computer_vision_system

**Comment by khaledgabr77** [comment]
thanks @ibaiGorordo. 
BTW i tested TfLite repo on axvier but it's still not working fine. 
i will test Pytorch repo and let you know.
